import streamlit as st
import time
from llm_engine import generate_dynamic_escape_room, build_system_prompt, interact_with_entity, parse_llm_response, generate_location_image

st.set_page_config(page_title="AI Escape Room", page_icon="🔐", layout="wide")

# --- Session State ---
if "setup_complete" not in st.session_state:
    st.session_state.setup_complete = False
if "room_data" not in st.session_state:
    st.session_state.room_data = {}
if "player" not in st.session_state:
    st.session_state.player = {"inventory": [], "clues": []}
if "active_entity_id" not in st.session_state:
    st.session_state.active_entity_id = None
if "chat_history" not in st.session_state:
    st.session_state.chat_history = []
if "last_game_logic" not in st.session_state:
    st.session_state.last_game_logic = {}


# --- VIEW 1: MAIN MENU ---
if not st.session_state.setup_complete:
    st.markdown("# 🔐 The Architect's Forge")
    
    with st.form("generation_form"):
        col_f1, col_f2 = st.columns(2)
        with col_f1:
             difficulty = st.select_slider("Difficulty", options=["Easy", "Normal", "Hard"], value="Normal")
        with col_f2:
             theme = st.text_input("Theme", placeholder="e.g., An abandoned alchemist's lab.")
        
        submitted = st.form_submit_button("Generate Escape Room ✨", type="primary")
        
        if submitted and theme.strip():
            with st.spinner("Constructing puzzles..."):
                new_room = generate_dynamic_escape_room(theme, difficulty)
                if new_room:
                    # Load the starting inventory generated by the LLM
                    st.session_state.player = {
                        "inventory": new_room.get("starting_items", []), 
                        "clues": []
                    }
                    
                    # Force DALL-E to draw the POIs
                    st.toast("Drafting visual blueprints...", icon="🎨")
                    poi_names = [obj['name'] for obj in new_room['interactables'].values()]
                    enhanced_img_prompt = f"{new_room['visual_description']} The scene MUST prominently feature these specific objects: {', '.join(poi_names)}."
                    
                    new_room['image_url'] = generate_location_image(enhanced_img_prompt)
                    
                    st.session_state.room_data = new_room
                    st.session_state.setup_complete = True
                    st.rerun()


# --- VIEW 2: THE ESCAPE ROOM ---
else:
    room = st.session_state.room_data
    master_puzzle = room["master_puzzle"]
    
    # HEADER
    st.markdown(f"## {room['name']}")
    st.markdown(f"_{room['visual_description']}_")
    
    # Show Starting Equipment notice
    if room.get("starting_items"):
        start_items_str = ", ".join([f"**{i['name']}**" for i in room["starting_items"]])
        st.info(f"You enter the room carrying only: {start_items_str}.")
    
    if room.get("image_url"):
        st.image(room["image_url"], use_container_width=True)
    st.divider()

    col_game, col_beholder = st.columns([3, 2], gap="medium")

    # --- LEFT COLUMN: Room & Inventory ---
    with col_game:
        st.subheader("🔒 Final Lockdown Mechanism")
        if master_puzzle["solved"]:
            st.success(master_puzzle["success_message"])
            st.balloons()
            if st.button("⬅️ Return to Forge"):
                 st.session_state.setup_complete = False
                 st.rerun()
        else:
            with st.form("keypad_form"):
                 cols_key = st.columns([3, 1])
                 with cols_key[0]:
                     code_guess = st.text_input("Enter Passcode:", label_visibility="collapsed")
                 with cols_key[1]:
                     if st.form_submit_button("Unlock"):
                         if code_guess.strip() == master_puzzle["solution"]:
                             st.session_state.room_data["master_puzzle"]["solved"] = True
                             st.rerun()
                         else:
                             st.error("🛑 ACCESS DENIED.")
        
        st.divider()
        st.subheader("🔎 Points of Interest")
        active_objs = {k:v for k,v in room["interactables"].items() if v["status"] == "active"}
        if active_objs and not master_puzzle["solved"]:
             cols = st.columns(3)
             for i, (obj_id, obj_data) in enumerate(active_objs.items()):
                 with cols[i % 3]:
                    if st.button(f"{obj_data['name']}", key=f"btn_{obj_id}", use_container_width=True):
                        st.session_state.active_entity_id = obj_id
                        st.session_state.chat_history = []
                        st.session_state.last_game_logic = {}
                        st.rerun()

        st.divider()
        col_inv, col_clues = st.columns(2)
        with col_inv:
            st.subheader("🎒 Backpack")
            for item in st.session_state.player["inventory"]:
                st.info(f"**{item['name']}**: {item['description']}")
        with col_clues:
            st.subheader("📓 Notebook")
            for clue in st.session_state.player["clues"]:
                st.warning(f"**{clue['name']}**: {clue['description']}")

    # --- RIGHT COLUMN: The Action Engine ---
    with col_beholder:
        if st.session_state.active_entity_id and not master_puzzle["solved"]:
            active_id = st.session_state.active_entity_id
            entity_data = room["interactables"][active_id]
            win_flag_name = entity_data["llm_config"]["win_flag"]
            
            st.subheader(f"Inspecting: {entity_data['name']}")
            
            # Show Chat/Action History
            with st.container(height=350, border=True):
                 for msg in st.session_state.chat_history:
                     avatar = "👤" if msg["role"] == "user" else "🤖"
                     st.chat_message(msg["role"], avatar=avatar).write(msg["content"])

            st.markdown("**Choose Action or Speak:**")
            action_to_take = None
            
            # 1. Rigid Buttons
            col_b1, col_b2, col_b3 = st.columns(3)
            if col_b1.button("👁️ Observe", use_container_width=True): 
                action_to_take = "OBSERVE: I carefully inspect this object. What do I see?"
            if col_b2.button("🖐️ Touch", use_container_width=True): 
                action_to_take = "TOUCH: I physically interact with, push, or attempt to open this."
            if col_b3.button("💡 Hint", use_container_width=True): 
                action_to_take = "HINT: Please give me a cryptic hint on how to bypass this."

            # 2. Use Item Combiner
            inv_names = [item["name"] for item in st.session_state.player["inventory"]]
            if inv_names:
                cols_use = st.columns([2, 1])
                with cols_use[0]:
                    selected_item = st.selectbox("Item", options=inv_names, label_visibility="collapsed")
                with cols_use[1]:
                    if st.button("🧩 Use Item", use_container_width=True): 
                        action_to_take = f"USE: I use my [{selected_item}] on this object."
            else:
                st.button("🧩 Use Item", disabled=True, use_container_width=True, help="Backpack empty.")

            # 3. Free Text Input
            if free_text := st.chat_input(f"Or type to interact with {entity_data['name']}..."):
                action_to_take = f"CUSTOM ACTION/SPEECH: {free_text}"

            # --- PROCESS THE CHOSEN ACTION ---
            if action_to_take:
                 # Clean up the display text for the user
                 display_text = action_to_take.replace("CUSTOM ACTION/SPEECH: ", "")
                 st.session_state.chat_history.append({"role": "user", "content": display_text})
                 
                 with st.spinner(f"Interacting with {entity_data['name']}..."):
                     sys_prompt = build_system_prompt(st.session_state.player, entity_data)
                     raw_response = interact_with_entity(sys_prompt, action_to_take)
                     dialogue, game_logic = parse_llm_response(raw_response, win_flag_name)
                     
                     st.session_state.last_game_logic = game_logic
                     st.session_state.chat_history.append({"role": "assistant", "content": dialogue})
                     st.rerun()

            # --- WIN CONDITION CHECK ---
            if st.session_state.get('last_game_logic', {}).get(win_flag_name) == True:
                    loot = entity_data.get("loot", {})
                    if loot.get("type") == "item":
                        st.toast(f"Acquired: {loot['name']}!", icon="🎒")
                        st.session_state.player["inventory"].append(loot)
                    else:
                         st.toast("Clue added to notebook!", icon="📓")
                         st.session_state.player["clues"].append(loot)
                    
                    st.session_state.room_data["interactables"][active_id]["status"] = "cleared"
                    st.session_state.active_entity_id = None
                    st.session_state.chat_history = []
                    st.session_state.last_game_logic = {}
                    time.sleep(1) 
                    st.rerun()